[licenses]
allow = [
    "MIT",
    "Apache-2.0",
]

[bans]
wildcards = "deny"
#external-default-features = "deny"

[bans.build]
#allow-build-scripts = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
