[licenses]
allow = [
    "MIT",
    "Apache-2.0",
]

[bans]
wildcards = "deny"
#external-default-features = "deny"

[bans.build]
allow-build-scripts = [
    { name = "magic-sys", version = "0.4" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
