version = 1
SPDX-PackageName = "The `magic` Rust crate"
SPDX-PackageSupplier = "robot9001 <robo9k@symlink.io>"
SPDX-PackageDownloadLocation = "https://github.com/robo9k/rust-magic"

[[annotations]]
path = ["Cargo.toml", "Cargo.lock", "README.md", "README-crate.md", "LICENSE.md", "CONTRIBUTING.md", "CHANGELOG.md", "SECURITY.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "© The `magic` Rust crate authors"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = [".github/workflows/**", ".github/ISSUE_TEMPLATE/**", ".github/pull_request_template.md", ".github/renovate.json5", "clippy.toml", "deny.toml", "release-plz.toml", "rust-toolchain.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "© The `magic` Rust crate authors"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "© The `magic` Rust crate authors"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = "data/tests/db-**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) Ian F. Darwin 1986, 1987, 1989, 1990, 1991, 1992, 1994, 1995."
SPDX-License-Identifier = "LicenseRef-file"
SPDX-FileComment = "https://github.com/robo9k/rust-magic/blob/main/LICENSE.md"

[[annotations]]
path = "data/tests/rust-logo-128x128-blk.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "The Mozilla Foundation"
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "https://github.com/robo9k/rust-magic/issues/12"
