blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/robo9k/rust-magic/discussions
    about: Please ask and answer questions here.
  - name: Security policy
    url: https://github.com/robo9k/rust-magic/security/policy
    about: Please view the security policy here.
  - name: magic-sys crate
    url: https://github.com/robo9k/rust-magic-sys
    about: Please find the separate magic-sys crate here.
