name: "docs"

permissions: {}

on:
  pull_request: 
  # run "deploy-pages" job to deploy main branch to GitHub pages
  push:
    branches: [ "main" ]

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_INCREMENTAL: "false"
  CARGO_PROFILE_TEST_DEBUG: "false"
  CARGO_TERM_VERBOSE: "true"
  CARGO_TERM_COLOR: "always"

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-rustdoc:
    name: "cargo docs-rs"
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - id: toolchain
        uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # doesn't have usual versioned releases/tags
        with:
          toolchain: nightly

      - run: echo "RUSTUP_TOOLCHAIN=${RUSTUP_TOOLCHAIN}" >> "${GITHUB_ENV}"
        env:
          RUSTUP_TOOLCHAIN: ${{ steps.toolchain.outputs.name }}

      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1

      - uses: taiki-e/install-action@7fe7b8c79a3c5569643cf27dfc32456883a4cd4d # v2.62.16
        with:
          # renovate: taiki-e/install-action
          tool: cargo-docs-rs@1.0.0

      - run: |
          crate_version=$(cargo metadata --format-version 1 --no-deps | jq --raw-output '.packages[] | select(.name == "magic").version')
          echo "ver=${crate_version}" >> "${GITHUB_OUTPUT}"

          repo_rev=$(git rev-parse --short=4 "${SHA}")
          echo "rev=${repo_rev}" >> "${GITHUB_OUTPUT}"
        id: crate-info
        env:
          SHA: ${{ github.event.pull_request.head.sha || github.sha }}

      - run: cargo docs-rs --version

      - run: RUSTDOCFLAGS="--crate-version ${VER}+${REV} --enable-index-page" cargo docs-rs --verbose --color always --locked --target-dir 'target/doc'
        env:
          VER: ${{ steps.crate-info.outputs.ver }}
          REV: ${{ steps.crate-info.outputs.rev }}

      - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Fix permissions
        run: |
          chmod -c -R +rX "target/doc/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
        with:
          path: target/doc/x86_64-unknown-linux-gnu/doc/

  deploy-pages:
    name: "deploy GitHub Pages"
    if: github.event_name == 'push'
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    needs: build-rustdoc
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
