name: "lint"

permissions: {}

on:
  pull_request:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  cargo-fmt:
    name: "cargo fmt"
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - id: toolchain
        uses: dtolnay/rust-toolchain@d8352f6b1d2e870bc5716e7a6d9b65c4cc244a1a # doesn't have usual versioned releases/tags
        with:
          toolchain: stable
          components: rustfmt # minimal profile does not include it

      - run: cargo +${{ steps.toolchain.outputs.name }} fmt --all --check

  cargo-clippy:
    name: "cargo clippy"
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - id: toolchain
        uses: dtolnay/rust-toolchain@d8352f6b1d2e870bc5716e7a6d9b65c4cc244a1a # doesn't have usual versioned releases/tags
        with:
          toolchain: stable
          components: clippy # minimal profile does not include it

      - run: cargo +${{ steps.toolchain.outputs.name }} clippy --all-targets --all-features

  cargo-rustdoc-clippy:
    name: "cargo rustdoc-clippy"
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - id: toolchain
        uses: dtolnay/rust-toolchain@d8352f6b1d2e870bc5716e7a6d9b65c4cc244a1a # doesn't have usual versioned releases/tags
        with:
          toolchain: nightly
          components: clippy # minimal profile does not include it

      # dependency of cargo-rustdoc-clippy
      - run: |
          sudo apt-get update
          sudo apt-get install zsh

      # https://github.com/rust-lang/rust/issues/56232#issuecomment-1248359946
      - run: |
          curl --output ~/.cargo/bin/cargo-rustdoc-clippy https://raw.githubusercontent.com/Nemo157/dotfiles/e6daf083068ff17d14b19dc2569ae62ea86bf23c/bin/cargo-rustdoc-clippy
          chmod +x ~/.cargo/bin/cargo-rustdoc-clippy

      - run: cargo +${{ steps.toolchain.outputs.name }} rustdoc-clippy --all-features
