name: "lint"

permissions: {}

on:
  pull_request:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  cargo-fmt:
    name: "cargo fmt"
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - id: toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # doesn't have usual versioned releases/tags
        with:
          toolchain: stable
          components: rustfmt # minimal profile does not include it

      - run: cargo +${{ steps.toolchain.outputs.name }} fmt --all --check

  cargo-clippy:
    name: "cargo clippy"
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - id: toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # doesn't have usual versioned releases/tags
        with:
          toolchain: stable
          components: clippy # minimal profile does not include it

      - run: cargo +${{ steps.toolchain.outputs.name }} clippy --all-targets --all-features

  cargo-rustdoc-clippy:
    name: "cargo rustdoc-clippy"
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - id: toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # doesn't have usual versioned releases/tags
        with:
          toolchain: nightly
          components: clippy # minimal profile does not include it

      # dependency of cargo-rustdoc-clippy
      - run: |
          sudo apt-get update
          sudo apt-get install zsh

      # https://github.com/rust-lang/rust/issues/56232#issuecomment-1248359946
      - run: |
          curl --output ~/.cargo/bin/cargo-rustdoc-clippy https://raw.githubusercontent.com/Nemo157/dotfiles/e6daf083068ff17d14b19dc2569ae62ea86bf23c/bin/cargo-rustdoc-clippy
          chmod +x ~/.cargo/bin/cargo-rustdoc-clippy

      - run: cargo +${{ steps.toolchain.outputs.name }} rustdoc-clippy --all-features
