name: "MSRV"

permissions: {}

on:
  pull_request:

env:
  RUSTFLAGS: "-Dwarnings"
  CARGO_INCREMENTAL: "false"
  CARGO_PROFILE_TEST_DEBUG: "false"
  CARGO_TERM_VERBOSE: "true"
  CARGO_TERM_COLOR: "always"

jobs:
  cargo-msrv:
    name: "cargo msrv"
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      # install toolchain/rustup for running `cargo msrv` itself
      # https://github.com/foresterre/cargo-msrv/blob/main/README.md#prerequisites
      - id: toolchain
        uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # doesn't have usual versioned releases/tags
        with:
          toolchain: "1.89.0" # current pinned stable

      - run: echo "RUSTUP_TOOLCHAIN=${RUSTUP_TOOLCHAIN}" >> "${GITHUB_ENV}"
        env:
          RUSTUP_TOOLCHAIN: ${{ steps.toolchain.outputs.name }}

      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1

      # install libmagic for dynamic linkage without robo9k/rust-magic-sys/setup-libmagic version
      - run: sudo apt-get update
      - run: sudo apt-get install libmagic1 libmagic-dev

      - uses: taiki-e/install-action@0e09747a63ae497bf945b3dcaf38fef0050d0109 # v2.62.0
        with:
          # renovate: taiki-e/install-action
          tool: cargo-msrv@0.18.4

      - run: cargo msrv --version
      - run: cargo msrv verify --output-format json -- cargo test --locked --all-targets --all-features
      - if: ${{ failure() }}
        run: cargo msrv find --output-format json -- cargo test --locked --all-targets --all-features
